2024-12-28T10:28:57,290 Using pip 24.3.1 from C:\Users\rapho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip (python 3.10)
2024-12-28T10:28:57,291 User install by explicit request
2024-12-28T10:28:57,393 Created temporary directory: C:\Users\rapho\AppData\Local\Temp\pip-build-tracker-7tr4pg2r
2024-12-28T10:28:57,393 Initialized build tracking at C:\Users\rapho\AppData\Local\Temp\pip-build-tracker-7tr4pg2r
2024-12-28T10:28:57,393 Created build tracker: C:\Users\rapho\AppData\Local\Temp\pip-build-tracker-7tr4pg2r
2024-12-28T10:28:57,393 Entered build tracker: C:\Users\rapho\AppData\Local\Temp\pip-build-tracker-7tr4pg2r
2024-12-28T10:28:57,394 Created temporary directory: C:\Users\rapho\AppData\Local\Temp\pip-install-zcm0r4ny
2024-12-28T10:28:57,417 Remote version of pip: 24.3.1
2024-12-28T10:28:57,417 Local version of pip:  24.3.1
2024-12-28T10:28:57,418 Was pip installed by pip? True
2024-12-28T10:28:57,419 ERROR: You must give at least one requirement to install (see "pip help install")
2024-12-28T10:28:57,419 Exception information:
2024-12-28T10:28:57,419 Traceback (most recent call last):
2024-12-28T10:28:57,419   File "C:\Users\rapho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
2024-12-28T10:28:57,419     status = _inner_run()
2024-12-28T10:28:57,419   File "C:\Users\rapho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
2024-12-28T10:28:57,419     return self.run(options, args)
2024-12-28T10:28:57,419   File "C:\Users\rapho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
2024-12-28T10:28:57,419     return func(self, options, args)
2024-12-28T10:28:57,419   File "C:\Users\rapho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_internal\commands\install.py", line 343, in run
2024-12-28T10:28:57,419     reqs = self.get_requirements(args, options, finder, session)
2024-12-28T10:28:57,419   File "C:\Users\rapho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_internal\cli\req_command.py", line 285, in get_requirements
2024-12-28T10:28:57,419     raise CommandError(
2024-12-28T10:28:57,419 pip._internal.exceptions.CommandError: You must give at least one requirement to install (see "pip help install")
2024-12-28T10:28:57,452 Removed build tracker: 'C:\\Users\\rapho\\AppData\\Local\\Temp\\pip-build-tracker-7tr4pg2r'
